### ISSUE TITLE
Remove compiler warnings and errors in GCC 4.8.2

### ISSUE THREAD

**Issue by saroberts** [goma/goma#13]
On the default Sandia build, we have a number of compiler warnings.  It's bad to keep these around, as they may mask newly bad things developed into the code.  

I would like to see all of these warnings resolved.  They can either be fixed, or if we don't care, the warning can be turned off (for example, you may not care about `-Wcomment` warnings).

**Comment by wortiz** [comment]
Should be no compiler warnings up to gcc 7.4
