### ISSUE TITLE
README.md and scripts/README.md require small corrections

### ISSUE THREAD

**Issue by AndrewUshakov** [goma/goma#142]
1) Line in scripts/README.md:

`export PATH="/[path to gomalibs]/trilinos-12.6.3-Build/bin:$PATH" `

need to be changed to:

`export PATH="/[path to gomalibs]/trilinos-12.10.1-Built/bin:$PATH"`

2) Line in README.md

`${gomadir}/TPLs/trilinos-12.6.3/bin/aprepro -v`

need to be changed to 

`${gomadir}/TPLs/trilinos-12.10.1-Built/bin/aprepro -v`

**Comment by legendvijay** [comment]
Hi,
Im new to ubuntu environment and building the things.
Im have doubt regarding the path we have to specify in the config file for ., make .
Kindly share the sample file which those paths specified and one more thing is i dont have SEACAS on TPLs. please clarify my doubts on that

**Comment by wortiz** [comment]
@legendvijay If you follow the instructions in https://github.com/goma/goma/blob/master/README.md

You should not need to specify any path. SEACAS is built into trilinos when using the build script

An example settings file can be found here: https://github.com/goma/goma/blob/master/settings.mk-example but isn't needed if you go with the README directions and use cmake
