### ISSUE TITLE
ARPACK website changed

### ISSUE THREAD

**Issue by ChungHHuang** [goma/goma#181]
I try to build GOMA with the commend ./easy-goma-builder.sh
ARPACK is not installing because the link is not working anymore. 
The error message is attached below:
--2018-06-18 16:13:32--  https://www.caam.rice.edu//software/ARPACK/SRC/arpack96.tar.gz
Connecting to www.caam.rice.edu (www.caam.rice.edu)|128.42.17.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by wortiz** [comment]
Thanks for the report it looks like we do indeed need to find another way to distribute arpack

As a temporary workaround it appears that fedora has the tarballs available:

https://src.fedoraproject.org/lookaside/extras/arpack/patch.tar.gz/14830d758f195f272b8594a493501fa2/patch.tar.gz

https://src.fedoraproject.org/lookaside/extras/arpack/arpack96.tar.gz/fffaa970198b285676f4156cebc8626e/arpack96.tar.gz

Which you should be able to download and put in your tars directory manually

**Comment by ChungHHuang** [comment]
Thank you for your help!
