### ISSUE TITLE
Build issues using easy-goma-builder.sh (Trilinos source and rpc/types.h)

### ISSUE THREAD

**Issue by torokati44** [goma/goma#200]
When trying to build Goma (master) using the `easy-goma-builder.sh` script, I encountered two issues.

First, the Trilinos source archive could not be downloaded from the location the script tries to (http://trilinos.csbsju.edu/download/files/trilinos-12.10.1-Source.tar.gz).
I found an alternative URL here: https://github.com/alces-software/packager-base/blob/master/libs/trilinos/12.10.1/trilinos-12.10.1-Source.tar.gz.fetch
Downloading the archive from there manually, and putting it in the `gomaTPLs/tars` directory worked.

Second, The `rpc/types.h` file could not be found on my system. Simply commenting out the [two problematic `#include` lines in sl_matrix_dump.c](https://github.com/goma/goma/blob/e6a800a96179070a7582b630ab011761e7fdb2e3/src/sl_matrix_dump.c#L44) made Goma build sucessfully.

My OS is Fedora 28 x64.

**Comment by wortiz** [comment]
Thanks for the info, I'll move them inside the ifdef

**Comment by torokati44** [comment]
#201 only fixes the second issue, but not the first.
Perhaps I should have reported them separately...

**Comment by wortiz** [comment]
You're right, I'll make another issue and fix that, thanks for double checking.
