### ISSUE TITLE
install error(./easy-goma-builder.sh: line 196: cmake: command not found)

### ISSUE THREAD

**Issue by Tso-Han-Li** [goma/goma#256]
I tried to install goma with "Download/Build Instructions", took a long time. Then it showed 
<./easy-goma-builder.sh: line 196: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
Something has gone wrong. Please create a GitHub issue.
Attach the logfile scripts/easygomabuild.txt,
and provide any information which might be helpful to debugging.

Thank you for using the Easy Goma Builder script
Have a nice day.>
I don't know where is wrong. Attach my "txt' file. Please help to debug. Thank you very much.
[easygomabuild.txt](https://github.com/goma/goma/files/3341757/easygomabuild.txt)
------------------------------------------------------
Attach my "print screen" picture
![easy-goma-builder sh-4](https://user-images.githubusercontent.com/52348228/60395173-37fdf000-9b62-11e9-9db8-0994d1ca5168.JPG)
.

**Comment by wortiz** [comment]
If you change the cmake export path line in the easy-goma-builder.sh to point to 3.9.5 instead of the 2.8 it is currently pointing to it should work, it looks like all your libraries built correctly

    -    export PATH="$PATH:$GOMA_LIB/cmake-2.8.12.2/bin"
    +    export PATH="$PATH:$GOMA_LIB/cmake-3.9.5/bin"


Alternatively you can copy the settings.mk-example to settings.mk and edit it to point to your build libraries

**Comment by wortiz** [comment]
Actually required a couple edits so you could download the version from here https://github.com/goma/goma/blob/d4df4ab80bd72b71918638943210ce0be96a90d1/scripts/easy-goma-builder.sh 

Or wait for the pull request to go through, or do the settings.mk version

**Comment by Tso-Han-Li** [comment]
My goma has been built successfully! But I check my "easy-goma-builder.sh", it shows  <export PATH="$PATH:$GOMA_LIB/cmake-2.8.12.2/bin">.
Maybe I do the cmake&make update, I guess. Attached my file, thank you very much!  😃

[easy-goma-builder.sh.txt](https://github.com/goma/goma/files/3349936/easy-goma-builder.sh.txt)
