### ISSUE TITLE
BC  CA_EDGE_CURVE does not work.

### ISSUE THREAD

**Issue by AndrewUshakov** [goma/goma#263]
Hi!

I just updated GOMA software and discovered that the new version produces results significantly different from my old results obtained in 2017 year.

Some time ago I modeled (for simplicity...) a free surface unstable flow of an extremely viscous liquid in a rectangular in cross section channel with a slightly negative slope and contact angle of the liquid with the side walls of the channel 60 degrees (120 in GOMA BC), gravity vector is opposite to the Y-axis, inlet shape and velocity distribution there are predefined, surface tension is significant. Below is my old converged (iteratively) solution:

![last_good](https://user-images.githubusercontent.com/7263403/62126441-5fb6b400-b2d8-11e9-9487-3dc262f847aa.png)

Using new GOMA (the same initial guess, input files, etc.) build I obtained different solution, where contact angle is definitely not a 60/120 degrees, and contact line reproduces initial guess:

![first_bad](https://user-images.githubusercontent.com/7263403/62126501-73fab100-b2d8-11e9-9311-758d3d1aa63a.png)

After some digging during 2 previous weeks I finally found that the reason of such GOMA behavior is a modification (added break statement) of the file bc_curve.c in the commit  "b02dcd73 Weston Ortiz <weston@wortiz.com> on 2/21/19 at 5:52 PM".

P.S. If you need I can send you all files required to reproduce the effect, but initial guess is rather big, so I don't know which variant is better?

**Comment by wortiz** [comment]
Thanks for the report, I'm pretty sure it should be fixed with this change as you said https://github.com/wortiz/goma/commit/695e56c74f5de2ec8e0624175dded3f3a8c424fb

That break was definitely and error and causing the BC to not be called

**Comment by AndrewUshakov** [comment]
Thank you for confirmation. I was not 100% sure that changes in different files are independent.
