### ISSUE TITLE
Element Variable output: Mapvar does not work with element variables

### ISSUE THREAD

**Issue by wortiz** [goma/goma#314]
Need to add option to disable element variables for mapvar, or some other solution

**Comment by tjiptowi** [comment]
If we use Scheme 2 options with MapVar, i.e. direct transfer, element variables mapping works.

**Comment by wortiz** [comment]
Note: If you can also use algebra to avoid the element variables:

    algebra in.exoII out.exoII

    > save nodal
    > save global
    > end

Then use mapvar as normal
