### ISSUE TITLE
Internal METIS decomposition using KWAY.

### ISSUE THREAD

**Issue by acochrane** [goma/goma#392]
New behavior in Goma 7.1.1
Is there a card for selecting decomposition besides KWAY?

The problem happens on my 3 node cluster.

> Internal METIS decomposition using KWAY.

I get an error in MPI

> [cinder:56052] *** An error occurred in MPI_Waitall
> [cinder:56052] *** reported by process [4208394241,43]
> [cinder:56052] *** on communicator MPI_COMM_WORLD
> [cinder:56052] *** MPI_ERR_TRUNCATE: message truncated
> [cinder:56052] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> [cinder:56052] ***    and potentially your MPI job)

**Comment by wortiz** [comment]
This seems to be fixed or non-reproducible now
