### ISSUE TITLE
parallel augmenting condition continuation fails to fix output

### ISSUE THREAD

**Issue by BWagoner901** [goma/goma#397]
I am using loca to continue in an augmenting condition float ( specifically the AC = Position condition). It proceeds as normal until fixing the output file. Example output below. I can put more of the stack trace if that would be helpful.

Example:

	 I will continue no more!
	 No more continuation for you!

Fixing exodus file out_test.exoII

-done

Proc 0 runtime:       5.36 Minutes.

[Singularity:696249] *** Process received signal ***
[Singularity:696249] Signal: Segmentation fault (11)
[Singularity:696249] Signal code: Address not mapped (1)

**Comment by wortiz** [comment]
More of the stack trace would be good.

It doesn't create the fixed output on this? it shouldn't print -done if it didn't make it through fix.

**Comment by rrrao** [comment]
Well at least Goma has a sense of humor wheat fails!
________________________________
From: Brayden Wagoner ***@***.***>
Sent: Tuesday, August 30, 2022 9:24:18 AM
To: goma/goma ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [goma/goma] parallel augmenting condition continuation fails to fix output (Issue #397)


I am using loca to continue in an augmenting condition float ( specifically the AC = Position condition). It proceeds as normal until fixing the output file. Example output below. I can put more of the stack trace if that would be helpful.

Example:

 I will continue no more!
 No more continuation for you!


Fixing exodus file out_test.exoII

-done

Proc 0 runtime: 5.36 Minutes.

[Singularity:696249] *** Process received signal ***
[Singularity:696249] Signal: Segmentation fault (11)
[Singularity:696249] Signal code: Address not mapped (1)

**Comment by BWagoner901** [comment]
Fixing exodus file out_test.exoII

-done


Proc 0 runtime:       5.36 Minutes.

[Singularity:696249] *** Process received signal ***
[Singularity:696249] Signal: Segmentation fault (11)
[Singularity:696249] Signal code: Address not mapped (1)
[Singularity:696249] Failing at address: 0x7f5210bed87c
double free or corruption (out)
[Singularity:696252] *** Process received signal ***
[Singularity:696252] Signal: Aborted (6)
[Singularity:696252] Signal code:  (-6)
[Singularity:696251] *** Process received signal ***
[Singularity:696251] Signal: Segmentation fault (11)
[Singularity:696251] Signal code: Address not mapped (1)
[Singularity:696251] Failing at address: 0x7f5210bed87c
[Singularity:696250] *** Process received signal ***
[Singularity:696250] Signal: Segmentation fault (11)
[Singularity:696250] Signal code: Address not mapped (1)
[Singularity:696250] Failing at address: 0x7f5210bed87c
[Singularity:696252] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7ff8a3cd0420]
[Singularity:696252] [ 1] [Singularity:696249] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f7eb79a5420]
[Singularity:696249] [ 1] [Singularity:696254] *** Process received signal ***
[Singularity:696254] Signal: Segmentation fault (11)
[Singularity:696254] Signal code: Address not mapped (1)
[Singularity:696254] Failing at address: 0x7f5210bed87c
/lib64/ld-linux-x86-64.so.2(+0x16d5d)[0x7f7eb82dcd5d]
[Singularity:696249] [ 2] /lib64/ld-linux-x86-64.so.2(+0x17f05)[0x7f7eb82ddf05]
[Singularity:696249] [ 3] [Singularity:696255] *** Process received signal ***
[Singularity:696255] Signal: Segmentation fault (11)
[Singularity:696255] Signal code: Address not mapped (1)
[Singularity:696255] Failing at address: 0x7f5210bed87c
[Singularity:696251] [ 0] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7ff8a3aef00b]
[Singularity:696252] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7ff8a3ace859]
[Singularity:696252] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x8d26e)[0x7ff8a3b3926e]
[Singularity:696252] [ 4] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x88)[0x7f7eb78e1928]
[Singularity:696249] [ 4] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x33)[0x7f7eb78e19f3]
[Singularity:696249] [ 5] /lib/x86_64-linux-gnu/libdl.so.2(+0x1b59)[0x7f7eb7a38b59]
[Singularity:696249] [ 6] /lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x28)[0x7f7eb7a38468]
[Singularity:696249] [ 7] double free or corruption (out)
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fb9bb667420]
[Singularity:696251] [ 1] /lib64/ld-linux-x86-64.so.2(+0x16d5d)[0x7fb9bbf9ed5d]
[Singularity:696251] [ 2] /lib64/ld-linux-x86-64.so.2(+0x17f05)[0x7fb9bbf9ff05]
[Singularity:696251] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x7dad6)[0x7f7eb762dad6]
[Singularity:696249] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_component_repository_release+0xcd)[0x7f7eb76082fd]
[Singularity:696249] [ 9] [ 3] [Singularity:696250] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f2b79c17420]
[Singularity:696250] [ 1] [Singularity:696248] *** Process received signal ***
[Singularity:696248] Signal: Aborted (6)
[Singularity:696248] Signal code:  (-6)
[Singularity:696254] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fb82af00420]
[Singularity:696254] [ 1] /lib64/ld-linux-x86-64.so.2(+0x16d5d)[0x7fb82b837d5d]
[Singularity:696254] [ 2] /lib64/ld-linux-x86-64.so.2(+0x17f05)[0x7fb82b838f05]
[Singularity:696254] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x952fc)[0x7ff8a3b412fc]
[Singularity:696252] [ 5] /lib/x86_64-linux-gnu/libc.so.6(+0x96fa0)[0x7ff8a3b42fa0]
[Singularity:696252] [ 6] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_components_close+0x5e)[0x7f7eb76090be]
[Singularity:696249] [10] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_framework_close+0x7c)[0x7f7eb761371c]
[Singularity:696249] [11] [Singularity:696255] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fe0fa9fa420]
[Singularity:696255] [ 1] /lib64/ld-linux-x86-64.so.2(+0x16d5d)[0x7fe0fb331d5d]
[Singularity:696255] [ 2] /lib64/ld-linux-x86-64.so.2(+0x17f05)[0x7fe0fb332f05]
[Singularity:696255] [ 3] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x88)[0x7fb9bb5a3928]
[Singularity:696251] [ 4] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x33)[0x7fb9bb5a39f3]
[Singularity:696251] [ 5] /lib64/ld-linux-x86-64.so.2(+0x16d5d)[0x7f2b7a54ed5d]
[Singularity:696250] [ 2] /lib64/ld-linux-x86-64.so.2(+0x17f05)[0x7f2b7a54ff05]
[Singularity:696250] [ 3] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x88)[0x7fb82ae3c928]
[Singularity:696254] [ 4] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x4f222)[0x7ff8a392a222]
[Singularity:696252] [ 7] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_datatype_finalize+0x79)[0x7ff8a45269c9]
[Singularity:696252] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x5f3)[0x7f7eb81e9c73]
[Singularity:696249] [12] /lib/x86_64-linux-gnu/libdl.so.2(+0x1b59)[0x7fb9bb6fab59]
[Singularity:696251] [ 6] /lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x28)[0x7fb9bb6fa468]
[Singularity:696251] [ 7] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x88)[0x7f2b79b53928]
[Singularity:696250] [ 4] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x773)[0x7ff8a4514df3]
[Singularity:696252] [ 9] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x33)[0x7fb82ae3c9f3]
[Singularity:696254] [ 5] /lib/x86_64-linux-gnu/libdl.so.2(+0x1b59)[0x7fb82af93b59]
[Singularity:696254] [ 6] /lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x28)[0x7fb82af93468]
[Singularity:696254] [ 7] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x33)[0x7f2b79b539f3]
[Singularity:696250] [ 5] /lib/x86_64-linux-gnu/libdl.so.2(+0x1b59)[0x7f2b79caab59]
[Singularity:696250] [ 6] /lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x28)[0x7f2b79caa468]
[Singularity:696250] [ 7] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x88)[0x7fe0fa936928]
[Singularity:696255] [ 4] /lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x33)[0x7fe0fa9369f3]
[Singularity:696255] [ 5] /lib/x86_64-linux-gnu/libdl.so.2(+0x1b59)[0x7fe0faa8db59]
[Singularity:696255] [ 6] /lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x28)[0x7fe0faa8d468]
[Singularity:696255] [ 7] [Singularity:696248] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f1195bae420]
[Singularity:696248] [ 1] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x7dad6)[0x7fb9bb2efad6]
[Singularity:696251] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x7dad6)[0x7fb82ab88ad6]
[Singularity:696254] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_component_repository_release+0xcd)[0x7fb82ab632fd]
[Singularity:696254] [ 9] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x7dad6)[0x7fe0fa682ad6]
[Singularity:696255] [ 8] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f11959cd00b]
[Singularity:696248] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f11959ac859]
[Singularity:696248] [ 3] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_component_repository_release+0xcd)[0x7fb9bb2ca2fd]
[Singularity:696251] [ 9] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_components_close+0x5e)[0x7fb9bb2cb0be]
[Singularity:696251] [10] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x7dad6)[0x7f2b7989fad6]
[Singularity:696250] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_framework_close+0x7c)[0x7fb9bb2d571c]
[Singularity:696251] [11] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_components_close+0x5e)[0x7fb82ab640be]
[Singularity:696254] [10] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_component_repository_release+0xcd)[0x7fe0fa65d2fd]
[Singularity:696255] [ 9] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_component_repository_release+0xcd)[0x7f2b7987a2fd]
[Singularity:696250] [ 9] /lib/x86_64-linux-gnu/libc.so.6(+0x8d26e)[0x7f1195a1726e]
[Singularity:696248] [ 4] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_components_close+0x5e)[0x7f2b7987b0be]
[Singularity:696250] [10] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_components_close+0x5e)[0x7fe0fa65e0be]
[Singularity:696255] [10] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x5f3)[0x7fb9bbeabc73]
[Singularity:696251] [12] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_framework_close+0x7c)[0x7fb82ab6e71c]
[Singularity:696254] [11] /lib/x86_64-linux-gnu/libc.so.6(+0x952fc)[0x7f1195a1f2fc]
[Singularity:696248] [ 5] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x5f3)[0x7fb82b744c73]
[Singularity:696254] [12] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_framework_close+0x7c)[0x7f2b7988571c]
[Singularity:696250] [11] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(mca_base_framework_close+0x7c)[0x7fe0fa66871c]
[Singularity:696255] [11] /lib/x86_64-linux-gnu/libc.so.6(+0x96fa0)[0x7f1195a20fa0]
[Singularity:696248] [ 6] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x5f3)[0x7fe0fb23ec73]
[Singularity:696255] [12] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x5f3)[0x7f2b7a45bc73]
[Singularity:696250] [12] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libopen-pal.so.40(+0x4f222)[0x7f1195808222]
[Singularity:696248] [ 7] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_datatype_finalize+0x79)[0x7f11964049c9]
[Singularity:696248] [ 8] /home/luser/Programs/goma-7/TPLs/openmpi-4.1.1/lib/libmpi.so.40(ompi_mpi_finalize+0x773)[0x7f11963f2df3]
[Singularity:696248] [ 9] goma(main+0x9f9)[0x563f5a614b69]
[Singularity:696252] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7ff8a3ad0083]
[Singularity:696252] [11] goma(main+0x9f9)[0x55bd0eed1b69]
[Singularity:696249] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f7eb77a5083]
[Singularity:696249] [14] goma(main+0x9f9)[0x56292e5e8b69]
[Singularity:696251] [13] goma(main+0x9f9)[0x55816cd8db69]
[Singularity:696254] [13] goma(_start+0x2e)[0x563f5a63459e]
[Singularity:696252] *** End of error message ***
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fb9bb467083]
[Singularity:696251] [14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fb82ad00083]
[Singularity:696254] [14] goma(main+0x9f9)[0x561354767b69]
[Singularity:696255] [13] goma(main+0x9f9)[0x555979b44b69]
[Singularity:696250] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fe0fa7fa083]
[Singularity:696255] [14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f2b79a17083]
[Singularity:696250] [14] goma(main+0x9f9)[0x55a9480d6b69]
[Singularity:696248] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f11959ae083]
[Singularity:696248] [11] goma(_start+0x2e)[0x55bd0eef159e]
[Singularity:696249] *** End of error message ***
goma(_start+0x2e)[0x56292e60859e]
[Singularity:696251] *** End of error message ***
goma(_start+0x2e)[0x55816cdad59e]
[Singularity:696254] *** End of error message ***
goma(_start+0x2e)[0x56135478759e]
[Singularity:696255] *** End of error message ***
goma(_start+0x2e)[0x555979b6459e]
[Singularity:696250] *** End of error message ***
goma(_start+0x2e)[0x55a9480f659e]
[Singularity:696248] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 3 with PID 0 on node Singularity exited on signal 11 (Segmentation fault).

**Comment by wortiz** [comment]
This looks like it is failing on MPI_Finalize.

Are you using the TPL openmpi or are you using another MPI? I'm wondering if there is a mismatch causing issues.


---

It looks like maybe you are using singularity to run stuff? I have a docker image that might work with that https://hub.docker.com/r/westonortiz/goma-libs we use it to run the test suite.

**Comment by BWagoner901** [comment]
Singularity is the name of my linux box here.

I believe I am using TPL openmpi. which mpirun returns the following:
goma-7/TPLs/openmpi-4.1.1/bin/mpirun

**Comment by wortiz** [comment]
Hmm. I'm guessing there is a bad MPI call with AC_POSITION I'll have to look at it.

If you have a shareable problem you can email me with AC_POSITION that would be good.

**Comment by BWagoner901** [comment]
Done!

**Comment by wortiz** [comment]
Should be fixed with #398, loca struct had wrong size for filenames
