### ISSUE TITLE
Improper AC initial guess read after LOCA continuation scheme

### ISSUE THREAD

**Issue by BWagoner901** [goma/goma#399]
Before LOCA continuation scheme

		 Values read time plane at time = -100
init_vec:  reading augmenting conditions initial guess from "IG.exoII.4.0" ...
AUGC[0] initial guess :  -127 found in exoII database - reading
AUGC[1] initial guess : -61.9 found in exoII database - reading

After LOCA continuation scheme concludes

		 Values read time plane at time = -3.87
init_vec:  reading augmenting conditions initial guess from "IG.exoII.4.0" ...
AUGC[0] initial guess :     0 found in exoII database - reading
AUGC[1] initial guess :     0 found in exoII database - reading

**Comment by wortiz** [comment]
I'm not sure I follow where this is happening.

Is it this:

You run something not LOCA to get IG.exoII

AUGC parameters exist

You are running LOCA to go to parameter -3.87

Then you use that as initial guess for a restart or something else and it shows 0 values?

**Comment by BWagoner901** [comment]
That is exactly correct.

**Comment by BWagoner901** [comment]
That seems to have done the trick. Thanks Weston!
