### ISSUE TITLE
Loca Element Quality Metrics

### ISSUE THREAD

**Issue by BWagoner901** [goma/goma#422]
Loca doesn't seem to break when the element quality metrics fall below the tolerance. 

Start of Step:    10   Continuation Param =   -3.6814 from   -3.6804
	Continuation method = First-order Continuation
	delta_c_p        = -9.26406e-04 
	delta_c_p_old    = -2.40625e-03

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:   10 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.681359e+00 delta_s= -9.264063e-04

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
13:14:10 [0] 7.7e-03 3.5e+00 1.6e-01 6.2e-01 9.8e+00 1.1e+00 5.9e-01/1.9e+00 0.0/0.0 0.0/0.0 
 Invoking damping factor 0.600000
          AC 9.3e-04 9.3e-04 9.3e-04 7.3e-03 7.3e-03 7.7e-03 4.9e-01/1.7e+00 0.0/0.0 0.0/0.0 
13:14:15 [1] 3.1e-03 1.4e+00 6.6e-02 3.6e-01 5.8e+00 5.7e-01 5.9e-01/1.8e+00 1.0/0.4 1.0/0.3 
 Invoking damping factor 0.600000
          AC 3.7e-04 3.7e-04 3.7e-04 2.9e-03 2.9e-03 3.1e-03 4.6e-01/1.7e+00 1.0/0.4 1.0/0.4 
13:14:20 [2] 1.2e-03 5.6e-01 2.6e-02 1.5e-01 3.2e+00 2.8e-01 5.8e-01/1.7e+00 1.0/0.4 1.2/0.3 
 Invoking damping factor 0.600000
          AC 1.5e-04 1.5e-04 1.5e-04 1.2e-03 1.2e-03 1.2e-03 4.5e-01/1.7e+00 1.0/0.4 1.0/0.4 
13:14:24 [3] 5.0e-04 2.3e-01 1.1e-02 6.5e-02 1.6e+00 1.3e-01 5.7e-01/1.8e+00 1.0/0.4 1.1/0.3 
 Invoking damping factor 1.000000
          AC 5.9e-05 5.9e-05 5.9e-05 4.7e-04 4.7e-04 4.9e-04 4.5e-01/1.7e+00 1.0/0.4 1.0/0.4 
13:14:29 [4] 3.2e-06 1.8e-05 3.8e-06 3.5e-03 1.2e-01 8.7e-03 6.0e-01/1.8e+00 8.7/5.0 3.7/1.6 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 1.9e-09 1.9e-09 2.0e-09 4.4e-01/1.8e+00 1.0/0.4 1.0/0.4 
13:14:34 [5] 9.9e-09 5.5e-08 1.2e-08 6.8e-06 2.9e-04 2.0e-05 5.7e-01/1.7e+00 0.7/2.0 2.2/3.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 8.6e-12 8.6e-12 9.1e-12 4.6e-01/1.8e+00 1.0/0.4 1.0/0.4 
13:14:38 [6] 9.8e-13 5.4e-10 2.0e-11 4.5e-10 4.9e-08 2.5e-09 5.9e-01/1.8e+00 1.1/2.9 1.5/4.5 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 8.3e-13 8.3e-13 8.8e-13 4.7e-01/1.8e+00 1.0/0.4 1.0/0.4 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
scaled solution norms   6.279e+02  6.278e+01  1.702e+02 

 ELEMENT QUALITY METRIC         AVG              MIN

	Step accepted, theta (proportion complete) = 3.438786e-01

------------------------------
Augmenting Conditions:       1
Number of extra unknowns:    1

	MT[ 400] XY[   0]=-3.681359e+00 Param=6.323404599e-02
               Jacobian         0.687856         0.419105
               Angle            0.985405          0.61639
               Triangle         0.946513         0.000780027
               COMBINED         0.858607         0.000780027     0.414354
Element quality below tolerance of 0.3
	REMESHING IS REQUIRED!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Continuation Step Number    10 was a success: Param =   -3.68136
	Order   = 1
	delta_c_p = -0.000926406

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Calculating initial guess for next continuation step

   Doing First-order continuation --
   calculating tangent vector by one linear solve
 Resolve_time:1.8e+00 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Start of Step:    11   Continuation Param =   -3.6828 from   -3.6814
	Continuation method = First-order Continuation
	delta_c_p        = -1.42667e-03 
	delta_c_p_old    = -9.26406e-04

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:   11 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.682785e+00 delta_s= -1.426666e-03

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
13:14:46 [0] 8.9e-13 4.5e-10 1.9e-11 1.3e+00 3.3e+01 2.9e+00 5.9e-01/1.7e+00 0.0/0.0 0.0/0.0

**Comment by wortiz** [comment]
I'm guessing you are expecting it to stop goma when it encounters elements below tolerance?

Or are you expecting it to treat that as a failed step? I'm guessing the former because I'm pretty sure that is what we do for everything else.

**Comment by BWagoner901** [comment]
You are exactly correct. 

Thank you!

**Comment by wortiz** [comment]
It should work with #423 now merged.

**Comment by BWagoner901** [comment]
good_mesh becomes 0 upon bad mesh quality but still no exit.

**Comment by wortiz** [comment]
How are you using loca? It was working for me on a test problem.

```
Element quality below tolerance of 0.7
        REMESHING IS REQUIRED!

         con_lib: INITIAL GUESS DID NOT CONVERGE:
                             ABORTING CONTINUATION RUN

CONTINUATION ROUTINE HAS FINISHED:
        Ending Parameter value     = 0
        Number of steps            = 0
        Number of Matrix fills     = 2
        Number of Residual fills   = 3



         I will continue no more!
         No more continuation for you!

-done
```

**Comment by BWagoner901** [comment]
I am using it to continue in the float value in an augmenting condition. It seems that upon a bad mesh, it thinks the solution has not converged and tries again with a smaller step size. In the output below, step 5 converges with a good mesh, goes to 6, that converges but with a bad mesh, it then tries again with smaller step size where it again reconverges with a bad mesh and loops again. I am looking for it to accept the converged solution at the first attempt at step 6 and exit for remeshing. I believe this is what happens when using hunting, but I couldn't get the ac float continuation feature to work in hunting.

Start of Step:     5   Continuation Param =   -3.4749 from   -3.4055
	Continuation method = First-order Continuation
	delta_c_p        = -6.94049e-02 
	delta_c_p_old    = -3.84160e-02

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:    5 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.474901e+00 delta_s= -6.940491e-02

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
09:42:36 [0] 4.6e-12 2.1e-09 9.7e-11 3.1e+00 3.3e+02 1.2e+01 5.5e-01/1.8e+00 0.0/0.0 0.0/0.0 
 Invoking damping factor 1.000000
          AC 6.9e-02 6.9e-02 6.9e-02 7.5e-04 7.5e-04 7.9e-04 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:42:41 [1] 2.7e-03 4.5e-02 4.8e-03 7.8e-01 1.7e+01 1.7e+00 5.5e-01/1.7e+00 0.7/-7.7 1.1/0.9 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 1.4e-06 1.4e-06 1.5e-06 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:42:46 [2] 1.2e-03 1.9e-02 2.1e-03 3.5e-01 6.4e+00 5.8e-01 5.4e-01/1.8e+00 -0.0/4.4 0.5/0.3 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 1.4e-06 1.4e-06 1.5e-06 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:42:50 [3] 5.2e-04 7.7e-03 8.7e-04 9.9e-02 2.5e+00 2.1e-01 5.3e-01/1.8e+00 1.1/0.4 1.0/0.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 7.2e-07 7.2e-07 7.6e-07 4.5e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:42:55 [4] 9.6e-06 5.4e-05 1.2e-05 2.4e-03 3.2e-02 4.0e-03 5.6e-01/1.8e+00 4.8/2.6 3.9/2.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 2.7e-08 2.7e-08 2.9e-08 4.7e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:00 [5] 3.5e-09 1.2e-07 1.5e-08 1.9e-07 1.8e-05 4.3e-07 5.5e-01/1.7e+00 1.6/3.4 2.3/5.1 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 9.8e-13 9.8e-13 1.0e-12 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:04 [6] 1.0e-12 5.7e-10 2.2e-11 3.8e-10 3.4e-08 1.9e-09 5.4e-01/1.8e+00 1.0/2.8 0.6/1.6 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 9.8e-13 9.8e-13 1.0e-12 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
scaled solution norms   6.154e+02  6.217e+01  1.693e+02 


 ELEMENT QUALITY METRIC         AVG              MIN
	goodmesh:
	Step accepted, theta (proportion complete) = 1.374209e-01

------------------------------
Augmenting Conditions:       1
Number of extra unknowns:    1

	MT[ 400] XY[   0]=-3.474901e+00 Param=6.086420813e-02
               Jacobian         0.688199         0.419106
               Angle             0.98671         0.745389

               Triangle         0.951752         0.339727
               COMBINED         0.860314         0.339727     0.533743
Element quality OK!
	goodmesh: 1 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Continuation Step Number     5 was a success: Param =    -3.4749
	Order   = 1
	delta_c_p = -0.0694049

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Calculating initial guess for next continuation step

   Doing First-order continuation --
   calculating tangent vector by one linear solve
 Resolve_time:1.8e+00 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Start of Step:     6   Continuation Param =   -3.5749 from   -3.4749
	Continuation method = First-order Continuation
	delta_c_p        = -1.00000e-01 
	delta_c_p_old    = -6.94049e-02

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:    6 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.574901e+00 delta_s= -1.000000e-01

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
09:43:12 [0] 1.0e-12 5.2e-10 2.2e-11 6.4e+00 4.5e+02 1.8e+01 5.4e-01/1.7e+00 0.0/0.0 0.0/0.0 
 Invoking damping factor 1.000000
          AC 1.0e-01 1.0e-01 1.0e-01 1.1e-03 1.1e-03 1.1e-03 4.5e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:43:16 [1] 1.4e-02 1.2e-01 1.8e-02 3.3e+00 5.7e+01 5.9e+00 5.5e-01/1.8e+00 0.6/-8.9 1.0/0.5 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 3.7e-05 3.7e-05 3.9e-05 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:21 [2] 8.7e-03 5.8e-02 1.0e-02 5.2e+00 7.3e+01 8.6e+00 5.4e-01/1.8e+00 -0.0/4.8 -0.3/-0.5 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 3.7e-05 3.7e-05 4.0e-05 4.6e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:43:26 [3] 1.0e-02 5.1e-02 1.2e-02 8.3e-01 1.7e+01 2.0e+00 5.4e-01/1.8e+00 -0.3/-0.2 -3.8/1.0 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 3.0e-06 3.0e-06 3.2e-06 4.5e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:43:30 [4] 4.6e-03 2.3e-02 5.4e-03 3.6e-01 5.5e+00 6.0e-01 5.5e-01/1.8e+00 -5.5/0.6 0.8/0.5 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 1.1e-06 1.1e-06 1.1e-06 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:35 [5] 1.9e-03 9.6e-03 2.2e-03 1.4e-01 2.4e+00 2.2e-01 5.5e-01/1.8e+00 1.1/0.4 0.8/0.4 
 Invoking damping factor 0.600000
          AC 0.0e+00 0.0e+00 0.0e+00 1.4e-07 1.4e-07 1.5e-07 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:40 [6] 7.8e-04 3.9e-03 9.1e-04 4.6e-02 1.0e+00 8.7e-02 5.5e-01/1.8e+00 1.0/0.4 0.9/0.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 9.6e-09 9.6e-09 1.0e-08 4.5e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:45 [7] 3.8e-06 3.2e-05 6.6e-06 8.1e-04 2.4e-02 1.6e-03 5.5e-01/1.8e+00 5.5/3.0 4.2/2.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 1.5e-08 1.5e-08 1.6e-08 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:49 [8] 3.3e-09 1.0e-07 1.0e-08 1.4e-06 3.8e-05 2.8e-06 5.5e-01/1.8e+00 1.3/3.2 1.6/3.3 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 4.8e-12 4.8e-12 5.1e-12 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
scaled solution norms   6.175e+02  6.247e+01  1.697e+02 


 ELEMENT QUALITY METRIC         AVG              MIN
	goodmesh:
	Step accepted, theta (proportion complete) = 2.374209e-01

------------------------------
Augmenting Conditions:       1
Number of extra unknowns:    1

	MT[ 400] XY[   0]=-3.574901e+00 Param=6.200836712e-02
               Jacobian         0.688027         0.419106
               Angle            0.986127         0.709257

               Triangle          0.94935         0.110473
               COMBINED         0.859531         0.110473      0.47344
Element quality below tolerance of 0.3
	REMESHING IS REQUIRED!
	goodmesh: 0 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Continuation Step Number     6 experienced a convergence failure
	in the non-linear or linear solver
		Value of parameter at failed step    = -3.5249
		delta_c_p of the failed step         = -0.1
		Next value of delta_c_p              = -0.05

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Start of Step:     6   Continuation Param =   -3.5249 from   -3.4749
	Continuation method = First-order Continuation
	delta_c_p        = -5.00000e-02 
	delta_c_p_old    = -6.94049e-02

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:    6 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.524901e+00 delta_s= 5.000000e-02

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
09:43:54 [0] 1.1e-03 5.2e-01 2.4e-02 3.2e+00 2.3e+02 9.1e+00 5.7e-01/1.8e+00 0.0/0.0 0.0/0.0 
 Invoking damping factor 0.600000
          AC 5.0e-02 5.0e-02 5.0e-02 5.4e-04 5.4e-04 5.7e-04 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:43:59 [1] 1.3e-03 2.2e-01 9.9e-03 1.3e+00 9.2e+01 4.2e+00 5.6e-01/1.7e+00 1.0/0.4 1.0/0.3 
 Invoking damping factor 0.600000
          AC 2.0e-02 2.0e-02 2.0e-02 2.2e-04 2.2e-04 2.3e-04 4.6e-01/1.8e+00 1.0/0.4 1.0/0.4 
09:44:04 [2] 9.0e-04 9.0e-02 4.1e-03 4.8e-01 3.6e+01 1.7e+00 5.4e-01/1.7e+00 1.0/0.4 1.1/0.4 
 Invoking damping factor 1.000000
          AC 8.0e-03 8.0e-03 8.0e-03 8.6e-05 8.6e-05 9.1e-05 4.6e-01/1.8e+00 1.0/0.4 1.0/0.4 
09:44:08 [3] 1.3e-04 9.2e-04 1.9e-04 1.6e-02 3.3e-01 3.2e-02 5.3e-01/1.8e+00 3.5/1.8 4.5/2.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 4.0e-10 4.0e-10 4.2e-10 4.6e-01/1.7e+00 1.0/0.4 1.0/0.4 
09:44:13 [4] 3.7e-07 1.2e-06 4.0e-07 8.4e-05 1.5e-03 1.7e-04 5.4e-01/1.8e+00 2.0/3.3 1.3/2.5 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 1.0e-09 1.0e-09 1.1e-09 4.6e-01/1.7e+00 1.0/0.4 1.0/0.4 
09:44:18 [5] 9.0e-10 4.2e-08 5.9e-09 1.8e-08 8.3e-06 9.8e-08 5.3e-01/1.8e+00 0.7/1.4 1.4/3.8 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 1.2e-12 1.2e-12 1.3e-12 4.5e-01/1.8e+00 1.0/0.4 1.0/0.4 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
scaled solution norms   6.155e+02  6.232e+01  1.695e+02 


 ELEMENT QUALITY METRIC         AVG              MIN
	goodmesh:
	Step accepted, theta (proportion complete) = 1.874209e-01

------------------------------
Augmenting Conditions:       1
Number of extra unknowns:    1

	MT[ 400] XY[   0]=-3.524901e+00 Param=6.143732979e-02
               Jacobian         0.688106         0.419106
               Angle            0.986422         0.747516

               Triangle         0.950598         0.208052
               COMBINED         0.859931         0.208052     0.508259
Element quality below tolerance of 0.3
	REMESHING IS REQUIRED!
	goodmesh: 0 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Continuation Step Number     6 experienced a convergence failure
	in the non-linear or linear solver
		Value of parameter at failed step    = -3.4999
		delta_c_p of the failed step         = -0.05
		Next value of delta_c_p              = -0.025

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Start of Step:     6   Continuation Param =   -3.4999 from   -3.4749
	Continuation method = First-order Continuation
	delta_c_p        = -2.50000e-02 
	delta_c_p_old    = -6.94049e-02

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	----------------------------------
	First order continuation:
	Step number:    6 of  100 (max)
	Attempting solution at:
	ACID=  0 DFID=   -1 Parameter= -3.499901e+00 delta_s= 2.500000e-02

               R e s i d u a l         C o r r e c t i o n

   ToD   itn   L_oo    L_1     L_2     L_oo    L_1     L_2    asm/slv (sec)  ROrd/Rt UOrd/Rt 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
09:44:23 [0] 5.7e-04 2.6e-01 1.2e-02 1.6e+00 1.1e+02 4.6e+00 5.7e-01/1.8e+00 0.0/0.0 0.0/0.0 
 Invoking damping factor 1.000000
          AC 2.5e-02 2.5e-02 2.5e-02 2.7e-04 2.7e-04 2.9e-04 4.5e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:44:27 [1] 9.1e-04 7.8e-03 1.2e-03 5.7e-02 2.3e+00 1.9e-01 5.6e-01/1.8e+00 1.1/1.0 1.1/1.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 4.4e-08 4.4e-08 4.6e-08 4.6e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:44:32 [2] 1.1e-05 6.5e-05 1.4e-05 2.8e-03 6.9e-02 8.1e-03 5.4e-01/1.7e+00 1.9/2.4 1.0/1.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 2.5e-08 2.5e-08 2.6e-08 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
09:44:36 [3] 1.9e-08 1.6e-07 2.4e-08 5.2e-07 3.1e-05 1.7e-06 5.4e-01/1.8e+00 1.4/3.2 2.7/4.8 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 1.6e-11 1.6e-11 1.7e-11 4.6e-01/1.7e+00 0.0/0.0 0.0/0.0 
09:44:41 [4] 6.8e-12 3.2e-09 1.4e-10 3.7e-10 4.9e-08 2.5e-09 5.5e-01/1.8e+00 0.8/1.9 0.8/2.4 
 Invoking damping factor 1.000000
          AC 0.0e+00 0.0e+00 0.0e+00 6.4e-12 6.4e-12 6.8e-12 4.6e-01/1.8e+00 0.0/0.0 0.0/0.0 
-------- --- ------- ------- ------- ------- ------- ------- --------------- ------- -------
scaled solution norms   6.155e+02  6.224e+01  1.694e+02

**Comment by wortiz** [comment]
Thanks. I misunderstood the logic in continuation. It should work with #424
