### ISSUE TITLE
Minimum Resolved Timestep

### ISSUE THREAD

**Issue by acochrane** [goma/goma#94]
I'm not sure that I'm using this input deck card correctly.
The Goma manual states,
"Its role is to set a lower bound for the time step with respect to the Time step error
tolerance. When a converged time step is obtained by GOMA, the difference between
the predicted solution and final solution for that time step is compared to the Time step
error tolerance. If the difference exceeds this tolerance the step fails and the time step
is cut (usually by a factor of 2), UNLESS the time step falls below the Minimum
Resolved Time Step size. In this case the step is accepted, even if this error tolerance is
not achieved. This provides a mechanism for the modeler to control what phenomena is
resolved and what phenomena is ignored."

The behavior I observe,
I set the Minimum Resolved Timestep to be some value, x. Even when a time step fails to converge through Newton iteration, the time step still does not get cut below x. The simulation retries the same calculation for the same x that failed Newton convergence previously. Resulting in retrying the same timestep over and over, until, I assume, it runs out of timesteps.

Is this the expected behavior or can we fix it? I think the card should allow further timesteps with the same dt only if Newton convergence succeeds, and cuts the timestep if the Newton convergence fails, no matter what.

**Comment by rrrao** [comment]
Once it hits the minimum resolved time step, it should give up.

**Comment by acochrane** [comment]
So that's what it's supposed to do for the _Minimum time step_. 
I thought _Minimum Resolved Time Step_ was a mechanism that allows the modeller some control over what phenomena is resolved, and what phenomena is ignored.

**Comment by rbsecor** [comment]
You could perhaps make an exception for Newton iteration failures, but please do not “fix” this capability.  It is valuable in terms of allowing short time scale physics to be ignored, if desired.  It does precisely what the manual says.

Robert

**Comment by acochrane** [comment]
Ok, after discussion with Daniel, I better understand what this card is for.

It seems like for my situation I should just restart the the simulation with different _Time step error_ value.

But the problem remains, what to do when Newton Convergence fails, instead of just repeating the previous failed calculation. I suppose Rekha's solution is the safest, to give up IF it hits _Minimum Resolved Time Step_ upon failing Newton Convergence.

What's less safe, and what I thought, at first glance, the _Minimum Resolved Time Step_ card was for, was to ignore the _Time step error_ time step cutting mechanism, ONLY IF Newton Convergence succeeded.

**Comment by acochrane** [comment]
Now that I've tested what happens when cutting the time step ONLY IF Newton convergence succeeds, I think the best solution is to have Goma give up if the Newton convergence failure causes the dt to fall below the _Minimum Resolved Time Step_.

Does that contradict any expected behavior?

As it stands, if the Newton convergence succeeds on a time step significantly smaller than _Minimum Resolved Time Step_, then dt gets immediately reset to _Minimum Resolved Time Step_. Then convergence fails, and several failing time steps cut the time step down so that another small time step can succeed, causing dt to get reset to _Minimum Resolved Time Step_ again.
